import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header/page";
import Footer from "./components/footer/footer";

export const metadata: Metadata = {
  title: "Digital Waves Solution",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Header />
      {children}
      <Footer />
    </html>
  );
}
